### PR TITLE
Fix script to work on Windows 10 as well

### PR DESCRIPTION
**Pull request by crazedVic**
Pretty straightforward, tested on Windows 10, maybe test on Mac before accept?

### CODE REVIEW

**Comment by redbastie** [comment]
Theres a couple of other places it needs fixed as well. Look for `'/'` in the source files and update the PR please.

I just made changes to my other package with these fixes here: https://github.com/redbastie/tailwire/commit/78b4bcae633d85354ebb893f26917171b0055d10

I recommend checking out and using tailwire instead of skele.

Thanks alot for your help though, this helped me identify an issue with tailwire that I was able to fix because of you 🔥

**Comment by crazedVic** [comment]
> Theres a couple of other places it needs fixed as well. Look for `'/'` in the source files and update the PR please.
> 
> I just made changes to my other package with these fixes here: [redbastie/tailwire@78b4bca](https://github.com/redbastie/tailwire/commit/78b4bcae633d85354ebb893f26917171b0055d10)
> 
> I recommend checking out and using tailwire instead of skele.
> 
> Thanks alot for your help though, this helped me identify an issue with tailwire that I was able to fix because of you 🔥

yeah i'm still slogging thru the video and fixing things as they come up.  Guessing these bugs might exist in tailwire as well?

**Comment by redbastie** [comment]
Yeah, can you test tailwire and tell me if you get errors? I might need to add directory_separator in more places...

**Comment by redbastie** [comment]
Nevermind, I'm going to install this on parallels and test it out.

**Comment by redbastie** [comment]
I'm working on a more proper fix on windows 10 in parallels right now. I'll reply when I have another update.

**Comment by crazedVic** [comment]
I'm through the video now and seems I got everything working with these changes.

**Comment by redbastie** [comment]
Hey Victor, I tried using Windows in Parallels and couldn't get Apache to run via Laragon LOL

I have a question for you, can you go ahead and try these changes.

In the `ManagesFiles` class, try replacing this:

    $filePath = Str::replaceLast('.stub', '', $this->replace($replaces, $file->getRelativePathname()));

    if ($fileDir = implode('/', array_slice(explode('/', $filePath), 0, -1))) {
        $this->filesystem()->ensureDirectoryExists($fileDir);
    }

With this:

	$filePath = Str::replaceLast('.stub', '', $this->replace($replaces, $file->getRelativePathname()));
	$filePath = str_replace('/', DIRECTORY_SEPARATOR, $filePath);

    if ($fileDir = implode(DIRECTORY_SEPARATOR, array_slice(explode(DIRECTORY_SEPARATOR, $filePath), 0, -1))) {
        $this->filesystem()->ensureDirectoryExists($fileDir);
    }

Then you should be able to undo all other changes you made, as it's replacing the separator for every single file that gets made.

Let me know how this works.

**Comment by crazedVic** [comment]
i'm new to this pull request stuff just realized that i should have branched off my fork.  please do not merge this :)

**Comment by redbastie** [comment]
lol its ok

**Pull request closed without merging**
